live_config_reload = true

import = [
  "~/.config/alacritty/tokyo-night.toml"
]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 1
decorations = "Buttonless"

[window.padding]
# x = 8
# y = 8

[font]
size = 12


[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
